In [1]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import numpy as np

In [20]:
ticker = "AAPL"
start_date = "2010-01-01"

data = yf.download(ticker, start=start_date,auto_adjust=False)
if isinstance(data.columns, pd.MultiIndex):
    data.columns = data.columns.get_level_values(0)
data.columns.name = None
data.index.name = "Date"  # optional, makes the index column named when saving
data_dir = Path("/content/drive/MyDrive/datascience/apple")
data_dir.mkdir(parents=True, exist_ok=True)
data.to_csv(data_dir / "AAPL_raw.csv") # saves from having to load again

[*********************100%***********************]  1 of 1 completed

data checks

In [21]:
data.head()

            Adj Close     Close      High       Low      Open     Volume
Date
2010-01-04   6.406478  7.643214  7.660714  7.585000  7.622500  493729600
2010-01-05   6.417556  7.656429  7.699643  7.616071  7.664286  601904800
2010-01-06   6.315477  7.534643  7.686786  7.526786  7.656429  552160000
2010-01-07   6.303802  7.520714  7.571429  7.466071  7.562500  477131200
2010-01-08   6.345712  7.570714  7.571429  7.466429  7.510714  447610800

In [17]:
data.tail()

                 Close        High         Low        Open    Volume
Date
2026-06-17  295.950012  302.070007  294.359985  300.850006  42745100
2026-06-18  298.010010  300.570007  295.619995  298.109985  85962200
2026-06-22  297.010010  302.420013  296.760010  297.309998  44879900
2026-06-23  294.299988  301.640015  294.179993  297.540009  52010900
2026-06-24  293.079987  299.700012  292.940002  295.359985  52882100

In [23]:
rows, cols = data.shape
print(f"Rows: {rows}, Columns: {cols}")
data.info()
data.index.is_monotonic_increasing

Rows: 4143, Columns: 6
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4143 entries, 2010-01-04 to 2026-06-24
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  4143 non-null   float64
 1   Close      4143 non-null   float64
 2   High       4143 non-null   float64
 3   Low        4143 non-null   float64
 4   Open       4143 non-null   float64
 5   Volume     4143 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 226.6 KB

True

In [24]:
data.isna().sum()

Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [28]:
first_date  = data.index.min()
last_date   = data.index.max()
n_records   = len(data)
any_missing = data.isna().any().any()

print("First date:", first_date)
print("Latest date:", last_date)
print("Number of trading-day records:", n_records)
print("Any missing values:", any_missing)

# Example difference between opening and closing prices (can also take mean)
data["Close_minus_Open"] = data["Close"] - data["Open"]
print(data["Close_minus_Open"].head())
print("Mean difference between close and open prices",data['Close_minus_Open'].mean())

First date: 2010-01-04 00:00:00
Latest date: 2026-06-24 00:00:00
Number of trading-day records: 4143
Any missing values: False
Date
2010-01-04    0.020714
2010-01-05   -0.007857
2010-01-06   -0.121786
2010-01-07   -0.041786
2010-01-08    0.060000
Name: Close_minus_Open, dtype: float64
Mean difference between close and open prices 0.06308354567192385